### ISSUE TITLE
Cycle Timer Discrepancies in Different Browsers + Mobile

### ISSUE THREAD

**Issue by klaefee** [Patribots4738/ScoutingWebsite#18]
The cycle timer on the official scouting website when opened on Firefox is _slower and inaccurate_ to an actual stopwatch and to the cycle timer on the website that is compiled on Chrome.

See the below video for a visual example. The current compiled scouting site is on the _left_ and the one listed in resources is on the _right_. The discrepancy can be noticed almost immediately.
[link](https://youtu.be/B4upoJoWKYc)

Where this becomes more of a problem is that the discrepancy seems to repeat itself on mobile, where the stopwatch slows to an even more considerable point. Count seconds out loud and you can see.
[link](https://youtube.com/shorts/5dferj3NIt4?feature=share)

When the link is copy and pasted to Safari and Google on mobile, this behavior often emerges again. I don't know how recent this issue is, but if it is indeed real and not a misunderstanding on my part then it could create obstacles to good scouting in future competitions.

**Comment by GalexY727** [comment]
I personally feel that the stopwatch as a whole is a good idea but could be implemented better, as in checking the time difference from the moment the scouts hit the score button on two separate occasions. I don't think scouts are going to be reliable enough to use a feature like this... at least not at this stage.

**Comment by Oliver-Cushman** [comment]
Right now I'm going to try and recreate this issue and hopefully fix it. Tomorrow we should discuss improvements or the possible removal of the stopwatch at lunch. @GalexY727 @RudyG252

**Comment by Oliver-Cushman** [comment]
I didn't test with different browser but the time discrepancy seems to be solved on mobile. It is not an optimal solution and I'd rather pivot to using setTimeout rather than setInterval, but I don't want to go too deep into it right now considering we may overhaul other things with it soon.

**Comment by Oliver-Cushman** [comment]
> I didn't test with different browser but the time discrepancy seems to be solved on mobile. It is not an optimal solution and I'd rather pivot to using setTimeout rather than setInterval, but I don't want to go too deep into it right now considering we may overhaul other things with it soon.

The issue in the browser should also by solved with the same solution as the setInterval backup bug is gone

**Comment by Hadizah454** [comment]
@klaefee I tried on Microsoft Edge and it worked fine, maybe it's just a Firefox issue but I'm not sure, I'll continue to check out other browsers though.
