### ISSUE TITLE
Button to upload all cached data

### ISSUE THREAD

**Issue by Faraday-dot-py** [Patribots4738/ScoutingWebsite#3]
This would need some way of filtering out duplicate data, whether that be on the backend or the frontend side

**Comment by RandomPro8** [comment]
I have no idea how exactly you would do this though, as we don't want to make too many requests to firebase.

**Comment by Jacob1010-h** [comment]
This is fixed with firebase #6 .... when new data arrives under the same name, match number, team number, and alliance color. the data is overwritten
